default_events:
  - issues

default_permissions:
  issues: write
  metadata: read

name: Nazoratchi

hook_attributes:
  url: https://smee.io/LvxdUyO90HDm5haX

description: Bu bot open source (ochiq kodli) loyihalarni boshqarib turadi. Uning vazifasi issue yaratganni, pull request yuborganlarga xabarlar qoldirish.
